### ISSUE TITLE
Open / Save file Dialogs don't remember last opened folder

### ISSUE THREAD

**Issue by tyronx** [MrCrayfish/ModelCreator#44] opened 2015-05-18 20:05 UTC
This one requires me to do a lot of extra clicks each time i open or save files. Would be awesome if it can remember that.

**Comment by Phallopode** [comment] 2015-05-20 03:58
Are you on mac ? I am and have the same problem also it doesn't remember the texture folder. Everytime I click "Import" in the texture manager I have to search from the "/user" directory.

**Comment by tyronx** [comment] 2015-05-20 06:24
I'm Windows Pre4

**Comment by mateuszdrwal** [comment] 2015-05-24 09:46
im pretty sure this was fixed ages ago. if you can, please be sure that the feature has not been added alredy to the latest commit. if you cant compile it yourself, heres the latest commit: 
https://www.dropbox.com/sh/njg2i8kczk4jmes/AADSYJ7RdAY7V8kcUULeJ90ma?dl=0
and also, someone should close this issue

**Comment by Phallopode** [comment] 2015-05-24 18:47
In my OS X 10.9.5 this commit is worse than all. I don't have any 3d and texture rendering and can't quit the application other way than using the closing keyboard shortcut.

The only time the dialog box remember the folder is when I import textures (textures who I can't see in the commit you brought). The first time it is the "/user" directory and from the second time it stays the last folder imported to. But if I close the application after saving the model then reopen it and then load the model again, the import folder returns back to default "/user".

In the Universal-pre4 from the site, it is the same issues except that I have the rendering and I can quit the application from the File menu. Also in the texture manager, if I import a texture, save the model then close the application and reopen it and load the model, the texture vanish from the Texture Manager (the texture is unused on the model that's maybe this).

With this version I have also very frequent crashes.

I'm gonna test it on Windows 8 to see if it works for me as expected. Maybe it's an issue with my own OS X.

**Comment by mateuszdrwal** [comment] 2015-05-24 19:23
yes, i think indeed its a problem with mac os but you should not concider the disapearing textures and file paths after closing a bug. its not a bug in the code, you have to code it to do that. 

the path after closing the program for me does not seem like an verry usefull feature. and as of now it would be difficult to make, because as i know the program isn't leaving any kind of save file that it loads after opening.

the loading path from .json might also be a little bit hard because if you interfear with the code in the.json, the model wil be corrupted. alternatively, you could do it with comments in the .json but i dont even know if there are comments in .json and even if, that would be realy complicated

**Comment by mateuszdrwal** [comment] 2015-05-27 16:14
so the conclusion of this feature request is:
- make export .json, import .json, save project and loade project remember the path
right?
i dont see it as verry usefull but sure

**Comment by tyronx** [comment] 2015-05-27 16:21
>i dont see it as verry useful but sure

Right now I copy&paste the path it should remember everytime I save or open something. That extra step I would be spared if it remember the path.

**Comment by mateuszdrwal** [comment] 2015-05-27 16:29
umm, i dont want to start a war here, 1st i said sure 2nd one thing you can do for now is create a folder shortcut in your documents folder as that is the default path

**Comment by tyronx** [comment] 2015-05-27 16:35
Sure, no Problem! :-)

**Comment by mateuszdrwal** [comment] 2015-05-27 16:48
:)

**Closed** 2016-05-10 14:44 UTC
